config/routes.rb
Rails.application.routes.draw do
  
 
 devise_for :rathnes, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
 resources :landing_images
  resources :albums do
    member do
      delete :del_picture
    end
  end  
  
  root "pages#home"
  get "/dashboard" => "editors#dashboard" ,as: :dashboard
  get "/account" => "editors#account_management", as: :account_management
  
  get "/photoshoots" => "pages#photoshoots" ,as: :photoshoots
  get "/about" => "pages#about" ,as: :about
  get "/contact" => "pages#contact" ,as: :contact
  
  resources :pages, only:[:home]
   

 
end

app/models/landing_image.rb
class LandingImage < ApplicationRecord
#landing Image has one photo
  has_one_attached :photo

#landing Image photo sizes
  def medium
    return self.photo.variant(resize: '400x600!').processed
  end 
  
  def thumb
    return self.photo.variant(resize: '300x300!').processed
  end 
end

app/controllers/landing_images_controller.rb
class LandingImagesController < ApplicationController
#before anything verify user loged in?  
  before_action :authenticate_rathne!
  
  def index
    @landing_image = LandingImage.paginate(:page => params[:page], :per_page => 2)
  end  
  
  def new
    @landing_image = LandingImage.new
  end  
  
  def create
    @landing_image = LandingImage.new(landing_image_params)
    if @landing_image.save
      redirect_to landing_images_path 
    else
      render 'new'
    end
  end
  
  def show
     @landing_image = LandingImage.find(params[:id])
  end 
  
  def edit
    @landing_image = LandingImage.find(params[:id])
    respond_to do |format|
        format.html 
        format.js 
    end
  end
  
  def destroy
    @landing_image = LandingImage.find(params[:id])
    @landing_image.destroy
    redirect_to landing_images_path
  end
  
  def update
    @landing_image = LandingImage.find(params[:id])
    if @landing_image.update_attributes(landing_image_params)
     redirect_to landing_images_path
     flash[:success] = "Image updated"
    else
      render 'edit'
    end
  end  
  
  private
    def landing_image_params
      params.require(:landing_image).permit(:photo,:header,:caption)
    end 
    
    
end

app/helpers/landing_images_helper.rb
module LandingImagesHelper
 

  
end

app/views/landing_images/_edit.html.erb
  <div class="row">
    <div class=" col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
      <div class="current-image">
        <%=image_tag(@landing_image.thumb, class:"edit-image" )%>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xl-8">
      <div class="edit-form">
        <%=form_for @landing_image do |f|%>
          <div class="form-group">
            <%=f.text_field :header%>
          </div>
          
          <div class="form-group">
            <%=f.text_area :caption,:rows => "10"%>
          </div>
          
          <div class="form-group">
            <%=f.file_field :photo%>
          </div>

          <div class="form-group">
            <%=f.submit "Update",class:"edit-image-create-button btn btn-primary"%>
            <button type="button" class="btn btn-danger return-to-original" data-dismiss="modal">Discard</button>
          </div>
        <%end%>
      </div>
    </div>
  </div>

app/views/landing_images/_show.html.erb
<%=image_tag(@landing_image.photo,class: "show-img-show css-modal-content img-fluid", :id => "show-img-show")%>

app/views/landing_images/_update_modal.html.erb
<!--ADMIN LANDING IMAGES UPDATE/EDIT MODAL-->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <!-- Modal body -->
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/landing_images/_view_picture_modal.html.erb
<!--ADMIN LANDING IMAGES AJAX MODAL SHOW-->

<!-- The Modal -->
<div id="ShowImg" class="modal css-modal">
  <button type="button" class="btn btn-danger close" data-dismiss="modal">X</button>
  <div class="css-modal-body ">
        
  </div>
</div>

app/views/landing_images/edit.html.erb
<!--SEE AJAX-->

app/views/landing_images/edit.js.erb
$(".modal-body").html("<%= escape_javascript(render 'edit') %>")
$('#myModal').modal('show');

app/views/landing_images/index.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN LANDING IMAGES INDEX-->
<div class="landin-editor-index">
  <div class="container">
    <div class="section-title">
      <h4 class="landing-index-title text-left">landing images</h4>
      <%=link_to "+ New Image", new_landing_image_path, class:" btn-add-new-index-imge btn btn-primary"%>
    </div>
    <%if @landing_image.empty?%>
        <div class="empty-image-notice-alert">
          <h4 class="empty-image-notice-alert-txt text-center"> No images yet, Do you want to <%=link_to "Create",new_landing_image_path%> a one ?</h4>
        </div>
    <%else%>
    <div class="image-rows">
      <%@landing_image.each do |lm|%>
        <div class="media image-index-media">
          
          <%=link_to landing_image_path(lm.id),:remote => true, data: { target: '#ShowImg', toggle: 'modal' } do%>
            <%=image_tag(lm.photo, class:"index-mainImages", :id => "index-mainImages")%>
          <%end%>
          <div class="media-body">
            <h4 class ="mt-0 index-image-header-txt"><%=lm.header%></h4>
            <p><%=lm.caption%></p>
          </div>
          <div class="index-image-options ml-3 text-center">
            <%=link_to lm, method: :delete do%>
              <h4 class="btn btn-danger index-delete">  Delete</h4>
            <%end%>
            <br>
            <%=link_to "Update", edit_landing_image_path(lm), class:"btn btn-success index-update",:remote => true, data: { target: '#myModal', toggle: 'modal' }%>
          </div>
        </div>
        <%= render "update_modal" %>
        <%= render "view_picture_modal" %>
      <%end%>
    </div> 
    <%end%>
    <%= will_paginate @landing_image %>
  </div>
</div>

app/views/landing_images/new.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN LANDING IMAGES NEW-->
<div class="new-image-form">
  <div class="title-header-new-main-image"><h4 class="title-header-new-main-image-text"></h4>Create New Image</div>
  <div class="container">
    
    <div class="new-image-bx">
      <%=form_for :landing_image, url: landing_images_path do |f|%>
        <div class="form-group row">
          <%=f.label :header,class: "col-sm-2 col-form-label"%>
          <div class="col-sm-10">
            <%=f.text_field :header%>
          </div>
        </div>
        
        <div class="form-group row">
          <%=f.label :caption,class: "col-sm-2 col-form-label"%>
          <div class="col-sm-10">
            <%=f.text_area :caption, :rows => "8"%>
          </div>
        </div>
        
        <div class="form-group">
          <%=f.file_field :photo, :required => "true"%>
        </div>
        
        <div class="form-group">
          <%=f.submit "Create",class:"new-image-create-button btn btn-primary"%>
        </div>
      <%end%>
    </div>
  </div>  
</div>

app/views/landing_images/show.html.erb
<!--SEE AJAX-->

app/views/landing_images/show.js.erb
$(".css-modal-body").html("<%= escape_javascript(render 'landing_images/show') %>")
$('#ShowImg').modal('show');