config/routes.rb
Rails.application.routes.draw do
  
 
 devise_for :rathnes, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
 resources :landing_images
  resources :albums do
    member do
      delete :del_picture
    end
  end  
  
  root "pages#home"
  get "/dashboard" => "editors#dashboard" ,as: :dashboard
  get "/account" => "editors#account_management", as: :account_management
  
  get "/photoshoots" => "pages#photoshoots" ,as: :photoshoots
  get "/about" => "pages#about" ,as: :about
  get "/contact" => "pages#contact" ,as: :contact
  
  resources :pages, only:[:home]
   

 
end

app/models/album.rb
class Album < ApplicationRecord

# each album has many pictures  
  has_many_attached :pictures
 

#picture sizes
  def thumbnail input
    return self.pictures[input].variant(combine_options: {
      auto_orient: true,
      gravity: "south",
      resize: "300x300^",
      crop: "300x600+0+0"
      }).processed
  end   
   
  def big input
    return self.pictures[input].variant(combine_options: {
    gravity: "center",
    }).processed
  end   
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

##backend views
  
#before anything verify user loged in?  
   before_action :authenticate_rathne!


  def index
    @album = Album.paginate(:page => params[:page], :per_page => 8)
      respond_to do |format|
        format.html 
        format.js 
      end
  end
  
  def new
     @album = Album.new
  end
  
  def create
    @album = Album.new(album_params)
    @album.save
    if @album.save
      respond_to do |format|
        format.html {redirect_to albums_path puts "created and save"}
        format.js 
      end  
    else
      render 'edit'
      puts "cannot save"
    end    
  end
  
  def show
    @album = Album.find(params[:id])
  end  
  
  def edit
    @album = Album.find(params[:id])
    respond_to do |format|
      format.html 
      format.js 
    end
  end
  
  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      respond_to do |format|
        format.html {redirect_to album_path(@album)}
        format.js 
      end
    end
  end
  
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end  

#delete invidual picture in current album  
  def del_picture 
    #find active storage attachemnt (picture) and delete it from current album'
    @album_child_pic = ActiveStorage::Attachment.find(params[:id])
    @album_child_pic.purge_later
    redirect_back(fallback_location: albums_path)
  end  

  
  private
    def album_params
     params.require(:album).permit(:title,:picture_caption,:shooting_date, :location, pictures:[])
    end  
    
    
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_pic_viewer_modal_slideshow.html.erb
<!--ADMIN ALBUMS SLIDESHOW POPUP MODAL-->
<div id="album_pic_slideshow" class="modal album_pic_slideshow-modal">
  <span class="close cursor album_pic_slideshow_close" onclick="closeModal()">&times;</span>
  <div class="album_pic_slideshow-modal-content ">
    <%@album.pictures.each_with_index do |picture, index|%>
      <div class="mySlides ">
        <%=image_tag(picture,class: "modal-image-slide img-fluid")%>
      </div>  
    <%end%>
  </div>
  <!-- Next/previous controls -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>

app/views/albums/edit.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN ALBUMS EDIT-->
<div class="container album-edit-container">
  <div class="albums-edit-bx">
    <div class="edit_album_header-title">
      <h5 class="edit-album-header-title-text text-left">Edit album</h5>
    </div>  
      <div class="row">
        <div class="col-md-12 col-lg-12 col-xl-12">
          <div class="new-image-bx">
            <%=form_for @album  do |f|%>
              <div class="col-md-12">
                <div class="form-group edit-album-frm-grp">
                <%=f.text_field :title, :placeholder => "Album Title", :required => true%>
                <%=f.text_area :picture_caption, :placeholder => "Say something about this album..", :rows =>"2"%>  
                </div>
              </div>
              <div class="row -adit-album-other-opts-row">
                <div class="col-md-3">
                  <div class="date-edit-date">
                    <h6 class="select-date">
                      <%=f.date_field :shooting_date%>
                    </h6>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="location">
                    <h6 class="select-location">
                      <%=f.text_field :location,:placeholder => "Where did you took pictures?"%>
                    </h6>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="add-pics text-right"><%=f.file_field :pictures,multiple: true, :required => false%></div>
                </div>
                <div class="col-md-3">
                  <div class="album-edit-frm-buttons text-right">
                    <%=f.submit "Save", class: "btn-primary edit-album-opt-btn-primary"%>
                  <%=link_to "Discard", albums_path, class:"btn-danger edit-album-opt-btn-btn"%>
                  </div>
                  
                </div>
              </div>
            <%end%>
            <div class="display-current-album-images">
              <div class="row">
              <%@album.pictures.each do |picture|%>
                <div class="col-md-3">
                  <div class="edit-album-current-image-album-images">
                    <%=image_tag(picture, class:"edit-album-pictures-show")%>
                  </div>
                </div>
              <%end%>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>



<script src="assets/albums_upload_preview.js"></script>

app/views/albums/index.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN ALBUMS INDEX-->
<div class="landin-editor-index">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title">
          <h4 class="landing-index-title text-left">Albums</h4>
          <%=link_to "+ New Album", new_album_path, class:" btn-add-new-index-imge btn btn-primary"%>
        </div>
        <%if @album.empty?%>
            <div class="empty-image-notice-alert">
              <h4 class="empty-image-notice-alert-txt text-center"> No Albums yet, Do you want to <%=link_to "Create",new_album_path%> a one ?</h4>
            </div>
        <%else%>
        <div class="album-display-container">
        <div class="row">
          <%@album.each do |ps|%>
            <div class="col-sm-12 col-xs-12 col-md-3 col-lg-3 col-xl-3">
              
              <div class="card" >
                <%=link_to(image_tag(ps.pictures.last.variant(resize: "275x250!").processed, class: "img-fluid image-album-cover card-img-top"),ps)%> <!--setting first img as defualt image and link to its album-->
                <div class="card-body">
                  <p class="card-text"><%=ps.title%></p>
                  <p class="card-text"><%=ps.shooting_date%></p>
                </div>
              </div>
            </div>
          <%end%>
          </div>
        </div>
        <%end%>
     <%#= render "albums/new_album_modal" %>
      <%= will_paginate @album %>
      </div>
    </div>
  </div>
</div>

app/views/albums/new.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN ALBUMS NEW-->
<div class="container album-edit-container">
  <div class="albums-edit-bx">
    <div class="edit_album_header-title">
      <h5 class="edit-album-header-title-text text-left">Create an album</h5>
    </div> 
    <div class="upload-notice">
      <h5 class="upload-notice-txt">To get best benifit of photoshoot page, please upload minimum 5 pictures or increment  minumium pictures by 4. (ie 5, 9 ,13,17.. etc)  </h5>
    </div>
      <div class="row">
        <div class="col-md-12 col-lg-12 col-xl-12">
          <div class="new-image-bx">
            <%=form_for :album, url: albums_path do |f|%>
              <div class="col-md-12">
                <div class="form-group edit-album-frm-grp">
                <%=f.text_field :title, :placeholder => "Album Title", :required => true%>
                <%=f.text_area :picture_caption, :placeholder => "Say something about this album..", :rows =>"2"%>  
                </div>
              </div>
              
              <div class="row -adit-album-other-opts-row">
                <div class="col-md-3">
                  <div class="date-edit-date">
                    <h6 class="select-date">
                      <%=f.date_field :shooting_date%>
                    </h6>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="location">
                    <h6 class="select-location">
                      <%=f.text_field :location,:placeholder => "Where did you took pictures?"%>
                    </h6>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="add-pics text-right"><%=f.file_field :pictures,multiple: true, :required => true, :id => "pictureShoot_pictures"%></div>
                </div>
                <div class="col-md-3">
                  <div class="album-edit-frm-buttons text-right">
                    <%=f.submit "Save", class: "btn-primary edit-album-opt-btn-primary"%>
                  <%=link_to "Discard", albums_path, class:"btn-danger edit-album-opt-btn-btn"%>
                  </div>
                  
                </div>
              </div>
          </div>
        </div>
        <div class="col-md-12 col-lg-12 col-xl-12">
          <hr class="file-choose-underline">
            <div id="image-holder" class="row">
             <!--preview uploading images here-->  
            </div>
        </div>
        
        <%end%>
      </div>
  </div>
</div>
<script src="assets/albums_upload_preview.js"></script>

app/views/albums/show.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN ALBUMS SHOW-->
<div class="show-uploaded-album-images">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title">
          <h4 class="landing-index-title text-left">Album :<%=@album.title%></h4>
          <ul class="album-ul-opts">
           <li class="album-opts-btns"><%=link_to "- go back", albums_path, class:" btn-album-bk album-opt-bttns btn btn-primary"%></li>
            <%=link_to @album, method: :delete do%>
              <li class="album-opts-btns"></li><h4 class=" btn-album-del album-opt-bttns btn btn-danger">- Delete Album</h4>
            <%end%>
            
            <li class="album-opts-btns"><%=link_to "- Add Pictures/edit Album", edit_album_path(@album), class:" btn-album-add-mre album-opt-bttns btn btn-success"%></li>
          </ul>
        </div>
      </div>
      <div class="col-md-12">
        <div class="row">
          <%@album.pictures.each_with_index do |picture, index|%>
            <div class="col-md-3">
              <div class="album-shw-bx text-center ">
               <%=image_tag(picture,class:"album-shw-img over-shadow cursor",:onclick => "openModal(); currentSlide(#{index+=1})" )%> 
              <div class="picture-option text-right">
                  <%=link_to  del_picture_album_url(picture.id),method: :delete,data: { confirm: 'Are you sure?' }  do%>
                    <i class="fa fa-trash-o al-pic-del" aria-hidden="true"></i>
                  <%end%>
                </div>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
<%=render "albums/album_pic_viewer_modal_slideshow"%>










<script>
function openModal() {
  document.getElementById('album_pic_slideshow').style.display = "block";
}

function closeModal() {
  document.getElementById('album_pic_slideshow').style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  
  
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  
  slides[slideIndex-1].style.display = "block";
  
}
</script>