config/routes.rb
Rails.application.routes.draw do
  
 
 devise_for :rathnes, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
 resources :landing_images
  resources :albums do
    member do
      delete :del_picture
    end
  end  
  
  root "pages#home"
  get "/dashboard" => "editors#dashboard" ,as: :dashboard
  get "/account" => "editors#account_management", as: :account_management
  
  get "/photoshoots" => "pages#photoshoots" ,as: :photoshoots
  get "/about" => "pages#about" ,as: :about
  get "/contact" => "pages#contact" ,as: :contact
  
  resources :pages, only:[:home]
   

 
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
#admin view
  before_action :authenticate_rathne!
  
#admin dashboard view
  def dashboard
    @edit_landings = LandingImage.paginate(:page => params[:page], :per_page => 4)
    @edit_albums = Album.paginate(:page => params[:page], :per_page => 8)
  end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/_albums_rendere.html.erb
<!--ADMIN DASHBOARD TO ALBUMS-->

<div class="row">
  <%if !@edit_albums.empty?%>
  <%@edit_albums.each do |al|%>
      <div class="col-md-3 col-lg-3 col-xl-3">
        <div class="card" >
          <%=link_to album_path(al.id)do%>
            <%=image_tag(al.pictures.last.variant(resize: "275x250!").processed, class: "img-fluid image-album-cover card-img-top")%>
            <div class="card-body">
              <p class="card-text"><%=al.title%></p>
              <p class="card-text"><%=al.shooting_date%></p>
            </div>
          <%end%>
        </div>
      </div>
    <%end%>
  <%end%>
</div>
<div class="pagi">
  <%=will_paginate @edit_albums%>
</div>

app/views/editors/_landing_imgs_rendere.html.erb
<!--ADMIN DASHBOARD TO LANDING IMAGES-->
<div class="row">
  <%@edit_landings.each do |lm|%>
    <div class="col-md-3 col-lg-3 col-xl-3">
      <%=link_to landing_image_path(lm.id),:remote => true, data: { target: '#ShowImg', toggle: 'modal' } do%>
        <%=image_tag(lm.photo, class:"edit-dash-img img-fluid", :id => "index-mainImages")%>
      <%end%>
    </div>
   <%end%>
</div>
<div class="pagi">
  <%=will_paginate @edit_landings%>
</div>

app/views/editors/dashboard.html.erb
<%=render "layouts/editor_nav"%>
<!--ADMIN DASHBOARD-->
<div class="dash-items">
  <div class="container">
    <div class="col-md-12">
      <div class="section-title">
       <h4 class="landing-panel-title text-left">landing images</h4>
       <%=link_to "+ New Image", new_landing_image_path, class:" btn-new-dash btn btn-primary"%>
      </div>
      <%if @edit_landings.empty?%>
        <div class="empty-image-notice-alert">
          <h4 class="empty-image-notice-alert-txt text-center"> No Images yet, Do you want to <%=link_to "Create",new_landing_image_path%> a one ?</h4>
        </div>
      <%else%>
      <div class="dash-landin-images text-center">
        <%=render "landing_imgs_rendere"%>
      </div>
      <%= render "landing_images/view_picture_modal" %>
      <%end%>
    </div>
    
    <div class="col-md-12 albums-col">
      <div class="section-title">
       <h4 class="album-panel-title text-left">Albumbs</h4>
       <%=link_to "+ New Album", new_album_path, class:" btn-new-dash btn btn-primary"%>
      </div>
      <%if @edit_albums.empty?%>
        <div class="notice-alert">
          <h4 class="notice-alert-txt text-center"> No albums yet, Do you want to <%=link_to "Create",new_album_path%> a one ?</h4>
        </div>
      <%else%>
        <div class="dash-album-images text-center">
          <%=render "albums_rendere"%>
        </div>
      <%end%>
    </div>
</div>