config/routes.rb
Rails.application.routes.draw do
  
 
 devise_for :rathnes, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
 resources :landing_images
  resources :albums do
    member do
      delete :del_picture
    end
  end  
  
  root "pages#home"
  get "/dashboard" => "editors#dashboard" ,as: :dashboard
  get "/account" => "editors#account_management", as: :account_management
  
  get "/photoshoots" => "pages#photoshoots" ,as: :photoshoots
  get "/about" => "pages#about" ,as: :about
  get "/contact" => "pages#contact" ,as: :contact
  
  resources :pages, only:[:home]
   

 
end

app/views/layouts/_editor_nav.html.erb
<div class="edit-nav">
  <div class="edit-nav-box ">
    <div class="container">
      <div class="dash-tit"><h3 class= "edit-nav-li-txt-dash"><%=link_to "Dashboard", dashboard_path%></h3></div>
      <div class="ul-items">
        <ul class="edit-nav-ul ">
          
          <li class="edit-nav-li-home text-right"><h3 class= "edit-nav-li-txt"><%=link_to "Home", root_path%></h3></li>
          <li class="edit-nav-li-landing text-right"><h3 class= "edit-nav-li-txt"><%=link_to "Landing Images", landing_images_path%></h3></li>
          <li class="edit-nav-li-albums text-right"><h3 class= "edit-nav-li-txt"><%=link_to "Albums", albums_path%> </h3></li>
          <li class="edit-nav-li-albums text-right"><h3 class= "edit-nav-li-txt"><%=link_to "Account Mangement", edit_rathne_registration_path%> </h3></li>
          <%if rathne_signed_in?%>
            <li class="edit-nav-li-albums text-right"><h3 class= "edit-nav-li-txt eidt-nav-li-text-logout"><%= link_to "Log out", destroy_rathne_session_path, method: :delete %></h3></li>
          <%end%>
          
        </ul>
      </div>
      
    </div>
  </div>
</div>

app/views/layouts/_errors_notification.html.erb
<div class="notice-wrapper">
  <% if flash[:error] %>
    <div class="show notice error notice-error">
      <span class="notice-message">
        <%= alert_string(flash[:error]) %>
      </span>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="nav-border" id="reveal_nav">
  <div class="reveal-nav-contents text-center">
    <ul class="reveal-nav-ul">
     
      <li class="reveal-nav-li">
        <i class="fa fa-facebook-official logs-to-out" aria-hidden="true"></i>
      </li>
      
      <li class="reveal-nav-li">
        <i class="fa fa-tumblr-square logs-to-out" aria-hidden="true"></i>
      </li>
      
      <li class="reveal-nav-li">
        <i class="fa fa-instagram logs-to-out" aria-hidden="true"></i>
      </li>
      
      
    </ul>
  </div>
</div> 

app/views/layouts/_mob_nav.html.erb
<div class="mob-nav-bar-top" id ="mynavigation">
  
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
    <h3 class="-men-items-txt mob--men-itm-txt"><%=link_to "Home", root_path%></h3>
    <h3 class="-men-items-txt mob--men-itm-txt"><%=link_to "About", about_path%> </h3>
    <h3 class="-men-items-txt mob--men-itm-txt"><%=link_to "PhotoShoots", photoshoots_path%> </h3>
    <!--<div class="-men-item">-->
    <h3 class="-men-items-txt mob--men-itm-txt"><%=link_to "Contact me",contact_path%>  </h3>
    <!--</div>-->
    
    <div class="footer-social text-center footer-mob-">
      <ul class="-social-men-ul">
       <li class="-social-men-li">
          <i class="fa fa-facebook-official logs-to-out-abt" aria-hidden="true"></i>
        </li>
        
        <li class="-social-men-li">
          <i class="fa fa-tumblr-square logs-to-out-abt" aria-hidden="true"></i>
        </li>
        
        <li class="-social-men-li">
          <i class="fa fa-instagram logs-to-out-abt" aria-hidden="true"></i>
        </li>
      </ul>
    </div>
    
    <!--<div class="-footer-comp text-center mob-footer-d-dwn footer-mob-">-->
    <!--  <p>&copy; 2019 B&J Photography<p>-->
    <!--    <hr class="power-devider">-->
    <!--  <p class="power">1611</p>  -->
    <!--</div>-->
  </div>
  
  
</div>

app/views/layouts/_nav.html.erb
<div class="nav-cont" id="mainNav">
  
  <div class="-nav-items">
    <div class="header-logs text-center">
    <ul class="social-ul">
      <li class="social-li"><i class="fa fa-twitter social" aria-hidden="true"></i></li>
      <li class="social-li"><i class="fa fa-tumblr social" aria-hidden="true"></i></li>
      <li class="social-li"><i class="fa fa-instagram social" aria-hidden="true"></i></li>
    </ul>
  </div>
    <div class="comp-header text-center">
      <span><h3 class="comp-header-txt text-center"> B & J</h3></span>
      <span><h5 class="comp-sub-header-txt text-center">photography</h5></span>
    </div>
    
    
    <div class="nv-bx ">
    
    <div class="nv-items text-center">
      <ul class="nav-ul">
        <li class="nav-ul-il nav-item">
          <a class="navbar-link js-scroll-trigger" href="#page-top"> <h3 class="nav-ul-li-txt"> home</h3></a>
        </li>
        <li class="nav-ul-il nav-item">
           <a class="nav-link js-scroll-trigger" href="#about"><h3 class="nav-ul-li-txt">About</h3></a>
        </li>
        <li class="nav-ul-il nav-item">
            <a class="nav-link js-scroll-trigger" href="#Photoshoots"><h3 class="nav-ul-li-txt">Photoshoots</h3></a>
        </li>
        <li class="nav-ul-il nav-item">
           <a class="nav-link js-scroll-trigger" href="#Contact"><h3 class="nav-ul-li-txt">Contact</h3></a>
        </li>
        
      </ul>
    </div>
  </div>
  </div>
</div>

app/views/layouts/_rev_corsuel.html.erb
<div class="cor-bx tex-center">
  <div id="carouselExampleControls" class="carousel vert slide" data-ride="carousel" data-interval="900">
    
    <div class="carousel-inner">
      <div class="carousel-item active">
        <ul class="list-unstyled">
          <li class="media">
            <%=image_tag("u1.png", class:"avt-rev-img image mr-3")%>
            <div class="media-body">
              <h5 class="mt-0 mb-1 header-star-topic">
                Amazing Photographer
              </h5>
              <div class="stars">
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
              </div>
              
              <p class="sub-txt-rev-star text-left">
                This site definitely  appeals to the average person because the layout
              is so  simple  but very  VERY  effective.
              </p>
            </div>
          </li>
          <br><br>
          <li class="media">
            <%=image_tag("u2.png", class:"avt-rev-img image mr-3")%>
            <div class="media-body">
              <h5 class="mt-0 mb-1 header-star-topic">
                Amazing Photographer
              </h5>
              <div class="stars">
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
              </div>
              
              <p class="sub-txt-rev-star text-left">
                This site definitely  appeals to the average person because the layout
              is so  simple  but very  VERY  effective.
              </p>
            </div>
          </li>
        </ul> 
      </div>
      
      <div class="carousel-item ">
        <ul class="list-unstyled">
          <li class="media">
            <%=image_tag("u3.png", class:"avt-rev-img image mr-3")%>
            <div class="media-body">
              <h5 class="mt-0 mb-1 header-star-topic">
                Amazing Photographer
              </h5>
              <div class="stars">
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
              </div>
              
              <p class="sub-txt-rev-star text-left">
                This site definitely  appeals to the average person because the layout
              is so  simple  but very  VERY  effective.
              </p>
            </div>
          </li>
          <br><br>
          <li class="media">
            <%=image_tag("u1.png", class:"avt-rev-img image mr-3")%>
            <div class="media-body">
              <h5 class="mt-0 mb-1 header-star-topic">
                Amazing Photographer
              </h5>
              <div class="stars">
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
                <i class="fa fa-star rev-star" aria-hidden="true"></i>
              </div>
              
              <p class="sub-txt-rev-star text-left">
                This site definitely  appeals to the average person because the layout
              is so  simple  but very  VERY  effective.
              </p>
            </div>
          </li>
        </ul> 
      </div>
    </div>
    
    
    <!--<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">-->
    <!--    <span ><i class="fa fa-long-arrow-up" aria-hidden="true"></i></span>-->
    <!--</a>-->
    <%=link_to "#carouselExampleControls",class:"carousel-control-next",data:{slide: "next"} do%>
      <i class="fa fa-long-arrow-up" aria-hidden="true"></i>
    <%end%>
    <%=link_to "#carouselExampleControls",class:"carousel-control-prev",data:{slide: "prev"} do%>
      <i class="fa fa-long-arrow-down" aria-hidden="true"></i>
    <%end%>
    <!--<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">-->
    <!--  <span><i class="fa fa-long-arrow-down" aria-hidden="true"></i></span>-->
    <!--</a>-->
  </div>
</div>


<script>
  $('.carousel').carousel({
   interval: 5000
})
</script>

app/views/layouts/_side_menu.html.erb
<!--side menue black /desktop-->
<div class="-men-header deak header-menu " id= "men-header">
  <div class="logo-header text-center">
    <%=image_tag("big-log.svg", class: "about-men-log")%>
  </div>
  <div class="-men-itm-bx">
    <div class="-men-item">
      <h3 class="-men-items-txt"><%=link_to "Home", root_path%></h3>
    </div>
    
    <div class="-men-item">
      <h3 class="-men-items-txt"><%=link_to "About", about_path%> </h3>
    </div>
    
    <div class="-men-item">
      <h3 class="-men-items-txt"><%=link_to "PhotoShoots", photoshoots_path%> </h3>
    </div>
    
    <div class="-men-item">
      <h3 class="-men-items-txt"><%=link_to "Contact",contact_path%>  </h3>
    </div>
    
    <div class="footer-social text-center">
      <ul class="-social-men-ul">
       <li class="-social-men-li">
          <i class="fa fa-facebook-official logs-to-out-abt" aria-hidden="true"></i>
        </li>
        
        <li class="-social-men-li">
          <i class="fa fa-tumblr-square logs-to-out-abt" aria-hidden="true"></i>
        </li>
        
        <li class="-social-men-li">
          <i class="fa fa-instagram logs-to-out-abt" aria-hidden="true"></i>
        </li>
      </ul>
    </div>
  </div>
  
  <div class="-footer-comp text-center">
    <p>&copy; 2019 B&J Photography<p>
      <hr class="power-devider">
    <p class="power">1611</p>  
  </div>
</div>
<!--end of side menue black /desktop-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>B & J photography</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Rajdhani:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    
    <%= content_tag :body, class: "#{controller_name}-#{action_name}", :id => "" do %>
        <!-- set background colors for pages -->
    <% end %>
    
    <%= yield %>
    
    
     <!--bottom-error-notification--> <div class="container">
        <% if notice%>
        <div id="notice_wrapper">
         <i class="fa fa-check-circle-o notice-correct" aria-hidden="true"></i>
         <p class= "notice">  <%=notice%></p>
        </div>
        <%elsif alert%>
         <div id="error_wrapper">
          <i class="fa fa-exclamation-circle notice-error" aria-hidden="true"></i>
          <p class= "alert"> <%=alert%></p>
        </div>
      <%end%>
      </div> 
    <!--end of --> 
    <!--<script src="assets/jquery.easing.min.js"></script>-->
    <!--<script src="assets/scrolling-nav.js"></script>-->
   
  </body>
</html>